<?php

/**
 * Implements hook_theme().
 */
function booking_theme($existing, $type, $theme, $path) {
  return [
    'booking' => [
      'variables' => [
        'content' => 'from hook module',
      ],
    ],
    'admin' => [
      'variables' => [
        'content' => 'from hook module',
      ],
    ],
    'service' => [
      'variables' => [
        'content' => 'from hook module',
      ],
    ],
    'server' => [
      'variables' => [
        'content' => 'from hook module',
      ],
    ],
  ];
}

